import keyMirror from "key-mirror";

export default keyMirror({
  REQUEST_CURRENT_USER: null,
  REQUEST_CURRENT_USER_SUCCESS: null,
  REQUEST_CURRENT_USER_FAILURE: null,

  UPDATE_REGISTRATION_USERNAME: null,
  UPDATE_REGISTRATION_PASSWORD: null,
  UPDATE_REGISTRATION_PASSWORD_CHECK: null,

  REGISTER_USER: null,
  REGISTER_USER_SUCCESS: null,
  REGISTER_USER_FAILURE: null,

  VIEW_CONFIGURATION_SETUP: null,
  VIEW_BROWSER_SETUP: null,
  VIEW_COMMUNICATION_SETUP: null,

  SUBMIT_ACTIVATION_UPDATE: null,
  SUBMIT_ACTIVATION_UPDATE_SUCCESS: null,
  SUBMIT_ACTIVATION_UPDATE_FAILURE: null,

  SUBMIT_SUBSCRIPTION_UPDATE: null,
  SUBMIT_SUBSCRIPTION_UPDATE_SUCCESS: null,
  SUBMIT_SUBSCRIPTION_UPDATE_FAILURE: null,

  SUBMIT_PASSWORD_CHANGE: null,
  SUBMIT_PASSWORD_CHANGE_SUCCESS: null,
  SUBMIT_PASSWORD_CHANGE_FAILURE: null,

  VIEW_LOGIN: null,
  VIEW_CONFIGURATION: null,
  VIEW_ACCOUNT: null,

  UPDATE_LOGIN_USERNAME: null,
  UPDATE_LOGIN_PASSWORD: null,

  LOGIN_USER: null,
  LOGIN_USER_SUCCESS: null,
  LOGIN_USER_FAILURE: null,

  REQUEST_CONFIGURATION: null,
  REQUEST_CONFIGURATION_SUCCESS: null,
  REQUEST_CONFIGURATION_FAILURE: null,

  PERSIST_CONFIGURATION: null,
  PERSIST_CONFIGURATION_SUCCESS: null,
  PERSIST_CONFIGURATION_FAILURE: null,

  ADD_BANG: null,
  UPDATE_BANG: null,
  UPDATE_BANG_PATTERN: null,
  DELETE_BANG: null,

  UPDATE_SEARCH_ENGINE: null,

  VIEW_ACCOUNT_RECOVERY: null,
  UPDATE_RECOVERY_USERNAME: null,

  REQUEST_ACCOUNT_RECOVERY: null,
  REQUEST_ACCOUNT_RECOVERY_SUCCESS: null,
  REQUEST_ACCOUNT_RECOVERY_FAILURE: null,

  VIEW_ACCOUNT_RECOVERED: null,

  LOGOUT: null,
  LOGOUT_SUCCESS: null,
  LOGOUT_FAILURE: null,

  UPDATE_NEW_PASSWORD: null,
  UPDATE_NEW_PASSWORD_CHECK: null,

  DELETE_ALL_DATA: null
});
